### ISSUE TITLE
final checklist

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/vega-test#11]
- [x] make sure the new binary is changed to rc2 for both local and public testnet readme, in the proposal `info`.
~- [ ] prepare a rc2 binary for darwin-arm64.~ not putting this binary
- [x] check the sha256 of the 3 genesis file: 
  - [x] original exported genesis, `86f29f23f9df51f5c58cb2c2f95e263f96f123801fc9844765f98eca49fe188f`
  - [x] the modified genesis for public testnet, `89d1cb03d1dbe4eb803319f36f119651457de85246e185d6588a88e9ae83f386`
  - [x] for local testnet
- [x] make sure the genesis files that all the nodes use are the same. `89d1cb03d1dbe4eb803319f36f119651457de85246e185d6588a88e9ae83f386`
- [x] update public testnet readme.
- [x] check the "binance" node is protected and sentry node is working.
~- [ ] [validator time sync](https://github.com/cosmos/gaia/issues/1018#issue-1022998785)~ not a concern for this testnet
- [x] check reward withdraw.
- [x] change back voting period to 24h 
- [x] stop the chain and check it is able to resume
  - [x] checked killing a validator with low voting power (no effect on producing blocks)
  - [x] checked chain stopping by killing a validator with high voting power
- [x] check links in upgrade info for local testnet autodownload

**Comment by uditvira** [comment]
- [ ] move faucet atoms to interchain dev account `cosmos1hxv7mpztvln45eghez6evw2ypcw4vjmsmr8cdx`

**Comment by uditvira** [comment]
- [ ] stop and restart the chain

**Comment by okwme** [comment]
communication plan:
 - [ ] finalize text for communications here: https://docs.google.com/document/d/1rqrxow25en_6AapdsysQOQy39RVOwD7To67DoPVjsVo/edit
 - [ ] post text into interchain blog post
 - [ ] publish on Cosmos blog
 - [ ] post link in #validators-verified
 - [ ] post link in node operators
 - [ ] make tweet from cosmos hub twitter
 - [ ] get cosmos hub tweet retweeted by interchain foundation and cosmos handles
 - [ ] post link in various telegrams and slack channels with validators

**Comment by uditvira** [comment]
- [ ] check that we can send faucet tokens from interchain dev account using keplr

**Comment by uditvira** [comment]
when we send out tokens to people, send them extra and tell them to pay it forward when other people ask
