### ISSUE TITLE
public testnet todo

### ISSUE THREAD

**Issue by okwme** [cosmos/vega-test#4]
~~Modify local test net instructions so that:~~
 * ~~use the interchain dev account ( `cosmos1hxv7mpztvln45eghez6evw2ypcw4vjmsmr8cdx` ) to receive 90% of total supply~~
   * ~~current total supply is 281MM, total delgated is 183 MM so we want 317MM ( aka x / (x + 183) = .67) to be used for delegation~~
   * ~~increase the user account by 300MM for faucet~~
   * ~~increase the total supply so it will be 281MM + 317MM + 300MM~~
     * ~~what is the amount to give new validators who didn't want to transfer their keys? (100k)~~
  * ~~make delegation transactions from the user account to our 3 designated validators~~
  * ~~replace the consensus keys of the following 3 designated validators~~
    *  ~~certus one, binance, coinbase~~

**Comment by uditvira** [comment]
talking to @yaruwangway, discussing some todo's
- [ ] Run the binance node on digital ocean machine @yaruwangway 
- [ ] Run certus-one and coinbase nodes on Hypha VM's @uditvira 
- [ ] Share peering information to add to our config files @yaruwangway and @uditvira 
- [ ] Start chain together on Friday
- [ ] Re-delegate from delegator to coinbase and certus-one
- [ ] Write upgrade proposal @uditvira
- [ ] Do upgrade on Tuesday
- [ ] Tell people on #validator-verified to check the schedule @uditvira 
- [ ] Update the public-testnet readme with th peering info
- [ ] Merge guidelines on udit's branch with yaru's branch

**Comment by yaruwangway** [comment]
The 3 nodes will upgrade by different ways:
HYPHA Binance: cosmovisor, manual prepare the new binary
HYPHA CoinBase: cosmovisor, auto-download
HYPHA Certus-one: gaiad

Mininum-gas-price:
HYPHA Binance: `minimum-gas-prices = 0.001uatom`

@uditvira please add the other two nodes `minimum-gas-prices`.

**Comment by uditvira** [comment]
closing, this has been superseded by issue #11
